describe('Cypress Demo Account Creation', () => 
{
    it('Account Creation scenario', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms/accounts')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get('.container > .dropdown > .dropdown-toggle').click()
      cy.get('.container > .dropdown > .dropdown-menu > :nth-child(1) > span').click()
      cy.get('.modal-body > :nth-child(1) > :nth-child(2) > :nth-child(1) > label').click()
      cy.get('.modal-body > :nth-child(2) > .form-control').type('Test Account')
      cy.get('.modal-body > :nth-child(3) > .form-control').type('test@gmail.com')
      cy.get('.iti__arrow').click()
      cy.get('#iti-item-bd > .iti__country-name').click()
      cy.get('#account-phone-number').type('01941105564')
      cy.get('#js-google-address-input').type('Dhaka, Bangladesh')
      cy.get(':nth-child(7) > :nth-child(1) > .form-control').type('1207')
      cy.get(':nth-child(7) > :nth-child(2) > .form-control').type('Dhaka')
      cy.get(':nth-child(8) > .form-control').type('Bangladesh')
      cy.get('.form-field > .uninite-option-field > .form-control').click()
      cy.get('[data-value="xp3msnReWto7MQT6J"] > :nth-child(1) > .img-circle').click()
      cy.get('.modal-footer > .btn-primary').click()
    })
    it('Account Creation with invalid data', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms/accounts')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get('.container > .dropdown > .dropdown-toggle').click()
      cy.get('.container > .dropdown > .dropdown-menu > :nth-child(1) > span').click()
      cy.get('.modal-body > :nth-child(1) > :nth-child(2) > :nth-child(1) > label').click()
      cy.get('.modal-body > :nth-child(2) > .form-control').type('123 456')
      cy.get('.modal-body > :nth-child(3) > .form-control').type('123.mail.com')
      cy.get('.iti__arrow').click()
      cy.get('#iti-item-bd > .iti__country-name').click()
      cy.get('#account-phone-number').type('0123456789')
      cy.get('#js-google-address-input').type('Dhaka, Bangladesh')
      cy.get(':nth-child(7) > :nth-child(1) > .form-control').type('D107')
      cy.get(':nth-child(7) > :nth-child(2) > .form-control').type('Dhaka')
      cy.get(':nth-child(8) > .form-control').type('Bangladesh')
      cy.get('.form-field > .uninite-option-field > .form-control').click()
      cy.get('[data-value="xp3msnReWto7MQT6J"] > :nth-child(1) > .img-circle').click()
      cy.get('.modal-footer > .btn-primary').click()
    })
})