describe('Cypress Doted specs', () => 
{
    it('Change Ownership', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get('#wZKiGTXsiWEvGhbuX').click()
      cy.get('.popover-body > :nth-child(1) > :nth-child(1)').click()
      cy.get('.form-group > .uninite-option-field > .form-control').click()
      cy.get('[data-value="NMoeoBLtNWB85jMeE"] > :nth-child(1) > .img-circle').click()
      cy.get('.modal-footer > .btn-primary').click()
    })
    it('Archive', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get('#oPbDbR7CSkRS5KpW4').click()
      cy.get('.popover-body > :nth-child(1) > :nth-child(1)').click()
      cy.get('.form-group > .uninite-option-field > .form-control').click()
     
    })
        it('Add property', () => 
        {
          cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
          cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
          cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
          cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
          cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
          cy.get('.active > a').click()
          cy.get('.nav > :nth-child(4) > a').click()
          cy.get('#wZKiGTXsiWEvGhbuX').click()
          cy.get('.popover-body > :nth-child(1) > :nth-child(3)').click()
          cy.get('.modal-body > :nth-child(1) > :nth-child(2) > label > .btn-text').click()
          cy.get(':nth-child(2) > :nth-child(2) > label > .btn-text').click()
          cy.get('#js-google-address-input').type('Dhaka, Bangladesh')
          cy.get(':nth-child(4) > :nth-child(1) > .form-control').type('1207')
          cy.get(':nth-child(4) > :nth-child(2) > .form-control').type('Dhaka')
          cy.get(':nth-child(6) > :nth-child(1) > .form-control').type('Second')
          cy.get(':nth-child(6) > :nth-child(2) > .form-control').type('2A')
          cy.get('#createAnotherOne').click()
          cy.get('.modal-footer-right > .btn-primary').click()

    })
    it('Download payout report', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get('#wZKiGTXsiWEvGhbuX').click()
      cy.get('.popover-body > :nth-child(1) > :nth-child(5)').click()
      cy.get('#download-date-range').click()
      cy.get('[data-range-key="Last 7 Days"]').click()
      cy.get('.modal-footer > .btn-primary').click()
      cy.get('.button-container > .btn')
    })
    it('Download payout report', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get('#wZKiGTXsiWEvGhbuX').click()
      cy.get('.popover-body > :nth-child(1) > :nth-child(5)').click()
      cy.get('#download-date-range').click()
      cy.get('[data-range-key="This Month"]').click()
      cy.get('.modal-footer > .btn-primary').click()
      cy.get('.button-container > .btn').click()
    })
})