describe('Cypress Filtering', () => 
{
    it('Filtering Accounts portion', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(1) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(2) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get(':nth-child(2) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get('.uninite-option-field > .form-control').click()
      cy.get('[data-value="NMoeoBLtNWB85jMeE"] > :nth-child(1) > :nth-child(3)').click()
    })
    it('Filtering Accounts portion diff agent', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(1) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(2) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get(':nth-child(2) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get('.uninite-option-field > .form-control').click()
      cy.get('[data-value="xp3msnReWto7MQT6J"] > :nth-child(1) > :nth-child(3)').click()
    })

it('SEND SMS TO ALL', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(1) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(2) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get(':nth-child(2) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get('.uninite-option-field > .form-control').click()
      cy.get('[data-value="xp3msnReWto7MQT6J"] > :nth-child(1) > :nth-child(3)').click()
      cy.get('.container > .dropdown > .dropdown-toggle > .icon-down-open').click()
      cy.get('.container > .dropdown > .dropdown-menu > :nth-child(2) > span').click()
      cy.get('.clearfix > .form-group > .form-control').type('This is a test SMS')
      cy.get('.pull-right > .btn-primary').click()
    })
    it('SEND EMAIL TO ALL', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(1) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(2) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get(':nth-child(2) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get('.uninite-option-field > .form-control').click()
      cy.get('[data-value="xp3msnReWto7MQT6J"] > :nth-child(1) > :nth-child(3)').click()
      cy.get('.container > .dropdown > .dropdown-toggle > .icon-down-open').click()
      cy.get('.container > .dropdown > .dropdown-menu > :nth-child(3) > span').click()
      cy.get('.uninite-form-group > .form-control').type('Testing purpose')
      cy.get('.fr-element').type('This email is for testing purpose')
      cy.get('.pull-right > .btn-primary').click()
    })
    it('Download Table data', () => 
    {
      cy.visit('https://partnerforsqa.dev.uniteliving.com/dtms')
      cy.get('#partnerLoginForm > :nth-child(1) > .form-control').type('sohel@gain.io')
      cy.get('#partnerLoginForm > :nth-child(2) > .form-control').type('SQAengineer')
      cy.get('#partnerLoginForm > :nth-child(3) > .btn').click()
      cy.get('.dropdown.user-menu-dropdown > .dropdown-toggle > .user-avatar').click()
      cy.get('.active > a').click()
      cy.get('.nav > :nth-child(4) > a').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(1) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(2) > label > .btn-text').click()
      cy.get(':nth-child(1) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get(':nth-child(2) > .col-md-11 > :nth-child(1) > :nth-child(3) > label > .btn-text').click()
      cy.get('.uninite-option-field > .form-control').click()
      cy.get('[data-value="xp3msnReWto7MQT6J"] > :nth-child(1) > :nth-child(3)').click()
      cy.get('.container > .dropdown > .dropdown-toggle > .icon-down-open').click()
      cy.get('.container > .dropdown > .dropdown-menu > :nth-child(4) > span').click()
      cy.get('.button-container > .btn').click()
    })
})